apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: eda-poc
spec:
  replicas: 1
  selector:
    matchLabels: { app: kafka-ui }
  template:
    metadata:
      labels: { app: kafka-ui }
    spec:
      containers:
      - name: ui
        image: provectuslabs/kafka-ui:latest
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
          - name: KAFKA_CLUSTERS_0_NAME
            value: "my-cluster"
          - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
            value: "my-cluster-kafka-bootstrap.eda-poc:9092"
          - name: DYNAMIC_CONFIG_ENABLED
            value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: eda-poc
spec:
  selector: { app: kafka-ui }
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
